#!/bin/bash
RELATIVE_FILE="./02"
EXEC_FILE="/root/02"
CRON_FILE="/etc/cron.d/02cron"

if [ "$USER" != "root" ]; then
	echo "Must be root!"
	exit 1
fi

cp "$RELATIVE_FILE" "$EXEC_FILE"
chmod 755 "$EXEC_FILE"
echo "0 4 * * 1 root $EXEC_FILE" > "$CRON_FILE"
chmod 644 "$CRON_FILE"
