#!/bin/bash
FILE="/root/crontab_state.txt"
STATE=`cat /etc/crontab`

if [ ! -e $FILE ]; then
	echo "$STATE" > $FILE
	exit
fi
DIFF=`diff $FILE <(echo "$STATE")`
if [ -z "$DIFF" ]; then
	exit
fi
DATE=`echo "$STATE" | cut -d' ' -f6-9`
echo "File /etc/crontab was modified @ $DATE" | mail -s "CRONTAB MODIFIED" root
echo "$STATE" > $FILE
